apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deployment
  annotations:
    deployment.kubernetes.io/revision: "1"
spec:
  selector:
    matchLabels:
      app: demoapp
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoappv1
        image: tuxotron/demoapp:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      restartPolicy: Always
